<?php
/** @var $block \Syncitgroup\Sgform\Block\Form */
//$formData = $this->getFormData();
//?>
<form class="form contact"
      action="#"
      id="syncit-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      style="width: 100%"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Write Us') ?></span></legend><br />

        <div class="field name required">
            <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field last_name required">
            <label class="label" for="last_name"><span><?php /* @escapeNotVerified */ echo __('Last name') ?></span></label>
            <div class="control">
                <input name="last_name" id="last_name" title="<?php /* @escapeNotVerified */ echo __('Last name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
<div class="success"></div>
<!--<script>-->
<!--    require(['jquery', 'jquery/ui','mage/mage'], function ($) {-->
<!--        const url = 'syncit_form/form/submit';-->
<!--        (function() {-->
<!--            jQuery('#syncit-form').submit( function (event) {-->
<!--                jQuery('body').trigger('processStart');-->
<!--                event.preventDefault();-->
<!--                if (!jQuery(this).validation('isValid')) return;-->
<!--                const formData = jQuery(this).serialize();-->
<!--                jQuery.ajax({-->
<!--                    url: url,-->
<!--                    method: 'post',-->
<!--                    data: formData,-->
<!--                }).done(function (response) {-->
<!--                    jQuery('body').trigger('processStop');-->
<!--                    response = JSON.parse(response)-->
<!--                    if (parseInt(response.response_code) === 200 && response.success === true) {-->
<!--                        jQuery('#syncit-form').hide();-->
<!--                        document.body.scrollTop = document.documentElement.scrollTop = 0;-->
<!--                        jQuery('.success').html(response.message);-->
<!--                    } else if (parseInt(response.response_code) === 444 && response.success === false) {-->
<!--                        alert(response.message);-->
<!--                        jQuery("#captcha-container-syncit_form button").trigger('click');-->
<!--                    }  else if (parseInt(response.response_code) === 400 && response.success === false) {-->
<!--                        alert(response.message);-->
<!--                    }-->
<!--                    console.log(response);-->
<!--                })-->
<!--            })-->
<!--        })();-->
<!--    })-->
<!--</script>-->
<script>
    require(['jquery', 'form'], function($, form) {
        form();
    });
</script>
