<?php

/** @var $block \Codiac\Search\Block\Product\ExtraInfo */

$categoryYesInfo = $this->getCategoryHinein();
$categoryNoInfo = $this->getCategoryNichtHinein();

?>
<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 info-renderer">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 price-info-renderer">
        <div class="product-price-info render-info" data-source="odd" data-toggle="modal" data-target="#darfhinein">
            <i class="fa fa-check"></i>
            <span>Was darf <br> hinein?</span>
<!--            <span class="arrow-point"><i class="fa fa-chevron-down"></i></span>-->
        </div>
    </div>

    <div class="col-lg-6 col-md-6 col-sm-6 price-info-renderer">
        <div class="product-price-info render-info" data-toggle="modal" data-target="#nichtdarfhinein">
            <i class="fa fa-times"></i>
            <span>Was darf <br>nicht hinein?</span>
<!--            <span class="arrow-point"><i class="fa fa-chevron-down"></i></span>-->
        </div>
    </div>
</div>

<div class="modal fade" id="darfhinein" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close darf" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?php echo __('Was darf hinein?'); ?></h4>
            </div>
            <div class="modal-body">
                <div class="modal-info">
                    <?php echo $categoryYesInfo ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="close-btn" data-dismiss="modal"><?php echo __('Close'); ?></button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="nichtdarfhinein" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close darf" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?php echo __('Was darf nicht hinein?'); ?></h4>
            </div>
            <div class="modal-body">
                <div class="modal-info">
                    <?php echo $categoryNoInfo ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="close-btn" data-dismiss="modal"><?php echo __('Close'); ?></button>
            </div>
        </div>
    </div>
</div>
<!--<script type="text/javascript">-->
<!--    require([-->
<!--        'jquery'-->
<!--    ], function(jQuery){-->
<!--        (function($) {-->
<!--            jQuery('.product-price-info').on('click', function () {-->
<!--                jQuery('.price-info-renderer').css('position', '');-->
<!--                if (jQuery(this).children('.arrow-point').children().attr('class') === 'fa fa-chevron-down') {-->
<!--                    jQuery(this).children('.arrow-point').children().removeClass('fa-chevron-down').addClass('fa-chevron-up')-->
<!--                } else {-->
<!--                    jQuery(this).children('.arrow-point').children().removeClass('fa-chevron-up').addClass('fa-chevron-down')-->
<!--                }-->
<!--                jQuery(this).parent('.price-info-renderer').css('position', 'relative');-->
<!--                jQuery(this).siblings('.price-info-bottom').toggle();-->
<!--                jQuery(this).parent().siblings('.price-info-bottom').toggle();-->
<!--            });-->
<!--        })(jQuery);-->
<!--    });-->
<!--</script>-->