<?php
/**
 * Bus view template
 *
 * @var $block \Codiac\Search\Block\Slider
 */
//echo $block->getBaseUrl();
?>

<style>


</style>
<div class="diagonal-split-background-bus-top"></div>
<div class="container">
    <div class="row bus-content">
        <div class="flex-container">
            <div class="col-sm-6 col-lg-6 left-bus-content">
                <h6>ZUVERLÄSSIG - SICHER - STARK</h6>
                <h2>Warum PRAJO<text style="color:red;">'S</text> MULDEN?</h2>
                <div class="border"></div>
                <p>Unser Mulden- &amp; Containerservice Furhpark ist abfahrbereit und wartet auf Sie!</p>
                <p>Da wir individuell auf Kundenwünsche eingehen und lösungsorientiert arbeiten, bieten wir die Antwort an, die Sie für Ihr Vorhaben suchen. Prajo’s Mulden steht für eine faire Preispolitik, zuverlässiges arbeiten, sicherer Transport und starken Kundensupport.</p>
                <p>Jeder Auftrag wird verlässlich zu Ihrer Zufriedenheit erfüllt.</p>
            </div>
            <div class="col-sm-6 col-lg-6 right-bus-content">
                <img src="<?php echo $block->getBaseUrl() . 'pub/media/motor-vehicle.jpg'; ?>" class="img-bus">
            </div>

        </div>
    </div>
</div>
