<?php

/** @var $block \Codiac\Search\Block\Delivery */

date_default_timezone_set("Europe/Berlin");
$dayOfTheWeek = date("N");
$endTime = $block->getShippingHours();
$limitTime = new DateTime($endTime);
$timeNow = new DateTime();
$showTime = false;
if ($timeNow < $limitTime) {
    $showTime = true;
}
$isShippingAvailable = $block->getExclusionAvailability();
$truckImg = $this->getBaseUrl() . 'pub/media/truck_back.png';
?>
<style>
    /*
    Animate the stripes
    */
    @-webkit-keyframes move{
        0% {
            background-position: 0 0;
        }
        100% {
            background-position: 50px 50px;
        }
    }
    @-moz-keyframes move{
        0% {
            background-position: 0 0;
        }
        100% {
            background-position: 50px 50px;
        }
    }
    @-ms-keyframes move{
        0% {
            background-position: 0 0;
        }
        100% {
            background-position: 50px 50px;
        }
    }
    @keyframes move{
        0% {
            background-position: 0 0;
        }
        100% {
            background-position: 50px 50px;
        }
    }
</style>

<div class="productbar" id="shipping-not">
    <?php if ($isShippingAvailable) { ?>
        <div class="bar"><span><img class="truck-message" src="<?php echo $truckImg ?>"><?php echo __($isShippingAvailable) ?></span></div>
    <?php } elseif ($showTime && $dayOfTheWeek != 6) { ?>
        <div class="bar"><span><img class="truck-message" src="<?php echo $truckImg ?>"><?php echo __('Bestellen Sie in der nächsten ') ?><span id="counting-time" style="display: inline;background: none"></span> <?php echo __(' Lieferung morgen!') ?></span></div>
    <?php } else { ?>
        <div class="bar"><span><img class="truck-message" src="<?php echo $truckImg ?>"><?php echo __('Lieferung innerhalb von zwei Tagen möglich.') ?></span></div>
    <?php } ?>
</div>

<?php if ($showTime && $dayOfTheWeek != 6) : ?>
<script>
    (function() {
        var start = new Date;
        var endingHour = '<?php echo (int)explode(':', $endTime)[0] ?>';
        start.setHours(endingHour, 0, 0); // 2pm
        function pad(num) {
            return ("0" + parseInt(num)).substr(-2);
        }
        function tick() {
            var now = new Date;
            if (now > start) { // too late, go to tomorrow
                start.setDate(start.getDate() + 1);
            }
            var remain = ((start - now) / 1000);
            var hh = pad((remain / 60 / 60) % 60);
            if(hh == '00'){
                var hour = ''
                hh = '';
            } else if(hh == '01'){
                var hour = 'Stunde'
            } else {
                var hour = 'Stunden';
            }
            var mm = pad((remain / 60) % 60);
            var ss = pad(remain % 60);
            document.getElementById('counting-time').innerHTML =
                hh + " " + hour + " " + mm + " Minute " + ss + " Sekunden ";
            setTimeout(tick, 1000);
        }
        document.addEventListener('DOMContentLoaded', tick);
    })();
</script>
<?php endif; ?>